version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run unittest
          command: python app/fizzbuzztest.py

workflows:
  version: 2
  say-fizz-pipeline:
    jobs:
      - unit_tests
