version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run unittest
          command: python app/fizzbuzztest.py

  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: bash scripts/build.sh
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker image to Docker Hub
          command: docker push winlost/sayfizzbuzz

  deploy:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: Install deployment script dependencies
          command: cd ansible && pipenv install
      - run:
          name: Deploy to production
          command: cd ansible && pipenv run ansible-playbook deploy-production.yml

workflows:
  version: 2
  say-fizz-pipeline:
    jobs:
      - unit_tests
      - build:
          requires:
            - unit_tests
      - deploy:
          requires:
            - build
